### ISSUE TITLE
What is the relationship with htmx and _hyperscript?

### ISSUE THREAD

**Issue by tqo50396** [Guseyn/EHTML#546]
Please have a look:

https://htmx.org/

https://hyperscript.org/

**Comment by Guseyn** [comment]
Okay, so EHTML focuses on **AJAX** interactions, mostly with **JSON** responses. 
**e-form**, for example, sends by default **JSON** payload.

Another important difference is HTMLX is focused on server side rendering and tries to manage the state on the server, while ETHML tries to manage application state on the client side by encapsulating it into DOM, localStorage, sessionStorage or some storage in memory. Also EHTML renders data on client side and has specific element that can be used for interactivity.

**Comment by Guseyn** [comment]
I would also add the fact that EHTML has more respect for conventions like for custom attributes, which must start with `data-`. Turbo/Stimulus also respects those conventions and follows them.
