### ISSUE TITLE
Fix docs typo: "e-google-oauth-button"

### ISSUE THREAD

**Issue by GDNacho** [Guseyn/EHTML#578]
In <e-github-oauth-button>'s documentation, this is at the bottom of the page:
![image](https://github.com/user-attachments/assets/5e93e878-90ca-45dd-805a-79c54addb8f5)
"google" instead of "github"

**Comment by Guseyn** [comment]
@GDNacho thank you, will fix it

**Comment by Guseyn** [comment]
@GDNacho this bug is fixed in https://github.com/Guseyn/ehtmlpage
